environment:
  PYTHON_HOME: "C:\\Python37"

  matrix:
    - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
    - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
    - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
    - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CONAN_VISUAL_VERSIONS: 16

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip install conan --upgrade
  - pip install bincrafters_package_tools
  - conan user # It creates the conan data directory

build_script:
  - python build.py
